### PR TITLE
Switched boolean flag to immediate flushing to integer

### LINKED ISSUE #718: immediate_buffer_flush should be in configuration file, defaulting to true.
### Expected behavior
Correct performance behavior, similar to Mosquitto or Aedes (less than 20ms for message to propagate from emitter to subscriber on localhost).
The parameter `immediate_buffer_flush` is not listed in the default conf file, and not mentioned in the documentation.
The default value does not seem appropriate for normal use cases.

### Actual behavior
Requests are buffered, resulting in delays of 1 second.

### Steps to reproduce
Run with default configuration.

### Moquette MQTT version
0.16, 0.17-SNAPSHOT

### JVM version (e.g. `java -version`)
n/a

### OS version (e.g. `uname -a`)
n/a

### PR DESCRIPTION
**Pull request by andsel**
## Release notes
Introduces the ability to specify the flush interval for IO write operations, changing the default, to an immediate flush.

## What does it do?
- Changed the value of configuration setting `immediate_buffer_flush` from boolean to a number (expressing milliseconds)
- Added 'buffer_flush_millis' setting which overrides the deprecated 'immediate_buffer_flush'
- Changed default behavior from "no flush on every write" to flush on each write.
- Used the value of the new `buffer_flush_millis` settings to initialize the auto flusher.

Fixes #718

### CODE REVIEW

**Review by hylkevds — COMMENTED** [review]
Looks good.
You've not updated the autoflush handler in NewNettyAcceptor yet, right?

**Comment by andsel** [comment]
@hylkevds have to do, I'm going with incremental commits, to make it easy reviewable. Still work in progress, once ready I'll ask you as reviewer.

File: broker/src/main/java/io/moquette/broker/BrokerConfiguration.java [hunk 1]
```diff
@@ -18,26 +18,57 @@
...
+                        }
+                    } catch (NumberFormatException ex) {
+                        throw new IllegalArgumentException(errorMsg);
+                    }
+            }
+        } else {
+            if (props.boolProp(BrokerConstants.IMMEDIATE_BUFFER_FLUSH_PROPERTY_NAME, true)) {
+                bufferFlushMillis = BrokerConstants.IMMEDIATE_BUFFER_FLUSH;
+            } else {
+                bufferFlushMillis = BrokerConstants.NO_BUFFER_FLUSH;
```
Comment (hylkevds) [inline broker/src/main/java/io/moquette/broker/BrokerConfiguration.java:61]: Maybe it's better to default to the 1s value that used to be used when `immediate_buffer_flush` was `false`?

**Review by hylkevds — DISMISSED** [review]
Looks good!

File: broker/src/main/java/io/moquette/broker/BrokerConfiguration.java (hunk 1 above)
Comment (andsel) [reply broker/src/main/java/io/moquette/broker/BrokerConfiguration.java:61]: Good point, done :+1:

Comment (jflamy) [reply broker/src/main/java/io/moquette/broker/BrokerConfiguration.java:61]: If you default to 1000ms people coming from Mosquitto will keep reporting bad performance

Comment (andsel) [reply broker/src/main/java/io/moquette/broker/BrokerConfiguration.java:61]: The old  `immediate_buffer_flush` default value is now switched from `false` to `true`.
So by default it now flushes immediatly, then if the user customize the `immediate_buffer_flush` to true, the flush interval is 1000ms

Comment (jflamy) [reply broker/src/main/java/io/moquette/broker/BrokerConfiguration.java:61]: You mean false I presume.immediate False = 1000; immediate true = 0.  Explicit numerical value ignored if immediate is true.
